#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
scripts_dir="$(pwd)/scripts"

${scripts_dir}/packages-fetcher
${scripts_dir}/deploy
${scripts_dir}/enable-hibernation


read -r -p "Do you want to install oh-my-zsh ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    ${scripts_dir}/install-oh-my-zsh
fi

read -r -p "Do you want to reboot ? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
    reboot
fi