#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

cp -r ${basedir}/../.config/* ${HOME}/.config/

sudo localectl set-keymap --no-convert fr_CH

xdg-mime default org.gnome.Nautilus.desktop inode/directory
xdg-mime default org.gnome.Nautilus.desktop x-directory/normal
xdg-mime default org.gnome.Nautilus.desktop x-directory/gnome-default-handler

sudo useradd -M greeter \
&& sudo cp -r ${basedir}/../etc/* /etc/ \
&& sudo chown -R greeter:greeter /etc/greetd/ \
&& sudo chmod -R go+r /etc/greetd/ \
# && sudo systemctl disable gdm \
# && sudo systemctl enable greetd \
&& sudo systemctl enable dbus-broker.service \
&& sudo systemctl enable bluetooth.service \
&& sudo systemctl enable logid.service \
&& sudo usermod -aG video $USER

sudo systemctl unmask firewalld
sudo systemctl start firewalld
sudo systemctl enable firewalld

sudo cp -a ${basedir}/../system/. /usr/lib/systemd/system/

if [ ! -d /run/clamav ]; then
    sudo mkdir /run/clamav
    sudo touch /run/clamav/clamd.ctl
fi
sudo setsebool -P antivirus_can_scan_system 1 \
&& sudo setsebool -P antivirus_use_jit 1 \
&& sudo freshclam \
&& sudo systemctl enable clamav-freshclam.service \
&& sudo systemctl enable clamav-clamonacc.service