#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

cp -a ${basedir}/../.config/. ${HOME}/.config/

sudo localectl set-keymap --no-convert fr_CH

xdg-mime default org.gnome.Nautilus.desktop inode/directory
xdg-mime default org.gnome.Nautilus.desktop x-directory/normal
xdg-mime default org.gnome.Nautilus.desktop x-directory/gnome-default-handler

sudo cp -a ${basedir}/../etc/. /etc/

sudo useradd -M -G greeter \
&& sudo chown -R greeter:greeter /etc/greetd/ \
&& sudo chmod -R go+r /etc/greetd/ \
&& sudo systemctl disable gdm.service \
&& sudo systemctl enable greetd.service \
&& sudo systemctl enable dbus-broker.service \
&& sudo systemctl enable bluetooth.service \
&& sudo systemctl enable logid.service \
&& sudo usermod -aG video $USER

sudo systemctl unmask firewalld
sudo systemctl start firewalld
sudo systemctl enable firewalld

sudo cp -a ${basedir}/../system/. /usr/lib/systemd/system/

if [ ! -d /run/clamav ]; then
    sudo mkdir /run/clamav
    sudo touch /run/clamav/clamd.ctl
fi
sudo freshclam \
&& sudo systemctl enable --now clamav-freshclam.service \
&& sudo systemctl enable clamav-clamonacc.service