#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

sudo dnf install -y \
    zsh
cp ${basedir}/../home/.zshrc ${HOME}/.zshrc
chsh -s $(which zsh)

curl -L git.io/antigen > ~/antigen.zsh