#!/usr/bin/env bash

cd "$(dirname ${BASH_SOURCE[0]})"
basedir="$(pwd)"

sudo dnf install -y \
    zsh

sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
cp ${basedir}/../home/.zshrc ${HOME}/.zshrc
chsh -s $(which zsh)
