#!/usr/bin/env bash

export packages=" \
    code \
    clamav \
    clamd \
    clamav-update \
    dbus-broker \
    flatpak \
    firewalld \
    ghostty \
    greetd \
    greetd-selinux \
    google-roboto-fonts \
    hypridle \
    hyprlock \
    hyprpaper \
    hyprpicker
    logiops \
    mako \
    niri \
    rofi \
    rofi-calc \
    papirus-icon-theme-dark \
    rustup \
    waybar \
    wlogout \
    wlroots \
    wlr-protocols-devel \
    xdg-desktop-portal \
    xdg-desktop-portal-gtk \
    xdg-desktop-portal-gnome \
    xwayland-satellite
    "